#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : requests-toolbelt
Version  : 0.8.0
Release  : 1
URL      : https://files.pythonhosted.org/packages/86/f9/e80fa23edca6c554f1994040064760c12b51daff54b55f9e379e899cd3d4/requests-toolbelt-0.8.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/86/f9/e80fa23edca6c554f1994040064760c12b51daff54b55f9e379e899cd3d4/requests-toolbelt-0.8.0.tar.gz
Summary  : A utility belt for advanced users of python-requests
Group    : Development/Tools
License  : Apache-2.0
Requires: requests-toolbelt-python3
Requires: requests-toolbelt-license
Requires: requests-toolbelt-python
Requires: requests
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
=================
        
        This is just a collection of utilities for `python-requests`_, but don't 
        really belong in ``requests`` proper. The minimum tested requests version is 
        ``2.1.0``. In reality, the toolbelt should work with ``2.0.1`` as well, but 
        some idiosyncracies prevent effective or sane testing on that version.
        
        ``pip install requests-toolbelt`` to get started!
        
        
        multipart/form-data Encoder
        ---------------------------
        
        The main attraction is a streaming multipart form-data object, ``MultipartEncoder``.

%package license
Summary: license components for the requests-toolbelt package.
Group: Default

%description license
license components for the requests-toolbelt package.


%package python
Summary: python components for the requests-toolbelt package.
Group: Default
Requires: requests-toolbelt-python3

%description python
python components for the requests-toolbelt package.


%package python3
Summary: python3 components for the requests-toolbelt package.
Group: Default
Requires: python3-core

%description python3
python3 components for the requests-toolbelt package.


%prep
%setup -q -n requests-toolbelt-0.8.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533055972
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/requests-toolbelt
cp LICENSE %{buildroot}/usr/share/doc/requests-toolbelt/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/requests-toolbelt/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
